# Generated by Django 4.2.16 on 2026-02-19 12:01

from django.db import migrations, models
import django.db.models.deletion
import load_cdf.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('load_cdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACE_AC_H0_SWE_v01_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.BigIntegerField(blank=True, null=True)),
                ('time_pb5_day_of_year', models.IntegerField(blank=True, null=True)),
                ('time_pb5_elapsed_milliseconds_of_day', models.IntegerField(blank=True, null=True)),
                ('time_pb5_year', models.IntegerField(blank=True, null=True)),
                ('alpha_ratio', load_cdf.models.Float32Field(blank=True, null=True)),
                ('np', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gse_x', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gse_y', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gse_z', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gsm_x', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gsm_y', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gsm_z', load_cdf.models.Float32Field(blank=True, null=True)),
                ('tpr', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_gse_vx', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_gse_vy', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_gse_vz', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_gsm_vx', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_gsm_vy', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_gsm_vz', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_rtn_vn', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_rtn_vr', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_rtn_vt', load_cdf.models.Float32Field(blank=True, null=True)),
                ('vp', load_cdf.models.Float32Field(blank=True, null=True)),
                ('cdf_file', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ACE_AC_H0_SWE_v01_data_data', to='load_cdf.cdffilestored')),
            ],
        ),
    ]
