# Generated by Django 4.2.16 on 2026-02-26 08:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import load_cdf.models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0001_initial'),
        ('data_cdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='INTERBALL_IT_H0_DOK_v01_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime_1', load_cdf.models.Float32Field(blank=True, null=True)),
                ('dtime_2', load_cdf.models.Float32Field(blank=True, null=True)),
                ('dtime_3', load_cdf.models.Float32Field(blank=True, null=True)),
                ('dtime_4', load_cdf.models.Float32Field(blank=True, null=True)),
                ('epoch_1', models.BigIntegerField(blank=True, null=True)),
                ('epoch_2', models.BigIntegerField(blank=True, null=True)),
                ('epoch_3', models.BigIntegerField(blank=True, null=True)),
                ('epoch_4', models.BigIntegerField(blank=True, null=True)),
                ('format_time', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), blank=True, null=True, size=3)),
                ('label_time', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), blank=True, null=True, size=3)),
                ('time_pb5_1', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=3)),
                ('time_pb5_2', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=3)),
                ('time_pb5_3', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=3)),
                ('time_pb5_4', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=3)),
                ('unit_time', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), blank=True, null=True, size=3)),
                ('a_theta_2', load_cdf.models.Float32Field(blank=True, null=True)),
                ('a_theta_4', load_cdf.models.Float32Field(blank=True, null=True)),
                ('ener_e_1', django.contrib.postgres.fields.ArrayField(base_field=load_cdf.models.Float32Field(null=True), blank=True, null=True, size=55)),
                ('ener_e_2', django.contrib.postgres.fields.ArrayField(base_field=load_cdf.models.Float32Field(null=True), blank=True, null=True, size=55)),
                ('ener_e_3', django.contrib.postgres.fields.ArrayField(base_field=load_cdf.models.Float32Field(null=True), blank=True, null=True, size=56)),
                ('ener_e_4', django.contrib.postgres.fields.ArrayField(base_field=load_cdf.models.Float32Field(null=True), blank=True, null=True, size=56)),
                ('fmode_1', models.PositiveIntegerField(blank=True, null=True)),
                ('fmode_2', models.PositiveIntegerField(blank=True, null=True)),
                ('fmode_3', models.PositiveIntegerField(blank=True, null=True)),
                ('fmode_4', models.PositiveIntegerField(blank=True, null=True)),
                ('gap_flag_1', models.IntegerField(blank=True, null=True)),
                ('gap_flag_2', models.IntegerField(blank=True, null=True)),
                ('gap_flag_3', models.IntegerField(blank=True, null=True)),
                ('gap_flag_4', models.IntegerField(blank=True, null=True)),
                ('label_e_1', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), blank=True, null=True, size=55)),
                ('label_e_2', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), blank=True, null=True, size=55)),
                ('label_e_3', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), blank=True, null=True, size=56)),
                ('label_e_4', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), blank=True, null=True, size=56)),
                ('se_1', django.contrib.postgres.fields.ArrayField(base_field=load_cdf.models.Float32Field(null=True), blank=True, null=True, size=55)),
                ('se_2', django.contrib.postgres.fields.ArrayField(base_field=load_cdf.models.Float32Field(null=True), blank=True, null=True, size=55)),
                ('si_3', django.contrib.postgres.fields.ArrayField(base_field=load_cdf.models.Float32Field(null=True), blank=True, null=True, size=56)),
                ('si_4', django.contrib.postgres.fields.ArrayField(base_field=load_cdf.models.Float32Field(null=True), blank=True, null=True, size=56)),
                ('cdf_file', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='INTERBALL_IT_H0_DOK_v01_data_data', to='load_cdf.cdffilestored')),
            ],
        ),
    ]
