# Generated by Django 4.2.16 on 2026-04-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='matchfile_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
