# Generated by Django 4.2.16 on 2026-02-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='depend_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
