# Generated by Django 4.2.16 on 2026-08-18 17:45

from django.db import migrations
import load_cdf.models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdffilestored',
            name='tu_end',
            field=load_cdf.models.Float32Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdffilestored',
            name='tu_start',
            field=load_cdf.models.Float32Field(blank=True, null=True),
        ),
    ]
