# Generated by Django 4.2.16 on 2026-04-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0002_upload_matchfile_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='matchfile_version',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
