# Generated by Django 4.2.16 on 2026-02-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0002_variable_depend_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='array_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='is_array_field',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
